### ISSUE TITLE
no longer builds for arm7

### ISSUE THREAD

**Issue by turbosnute** [turbosnute/tibberinfo-influxdb#2]
It seems like this container does not successfully builds on the arm architecture anymore

**Comment by kler** [comment]
On `aarch64` it does work (`Raspberry Pi 4 Model B Rev 1.5`).
What hardware are you running on?

**Comment by turbosnute** [comment]
Thanks for the quick reply!

I also run a RPi4. It's probably me misunderstanding a config issue of my own docker host. I'll check tomorrow.

Again, thanks very much for all your good work on that last PR.

**Comment by turbosnute** [comment]
My hardware is Raspberry Pi 4 Model B Rev 1.1

The problem occured when building the dependencies (aiohttp) for pyTibber==0.22.3 

I noticed in the errors that gcc and stdlib.h was missing, so I added gcc and libc-dev. It worked.

https://github.com/turbosnute/tibberinfo-influxdb/commit/fc945a97601f80f0822b00592ce8fa62e7ab806c
